name: unsbscribe_app
description: Unsubscribe app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.4.1
  pedantic_mono: ^1.21.1
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
